config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tags
  resources :clients
  resources :time_cards
  root to: 'clients#index'
  get 'index/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :listings do
    member do
      patch  :move
    end
  end

  resources :clients do
    member do
      get :to_do
    end
  end

  resources :time_cards do
    member do
      patch  :edit
    end
  end

  resources :cards do
    member do
      patch  :move
    end
  end
end

app/models/time_card.rb
class TimeCard < ApplicationRecord
	belongs_to :card
	has_many :tags
	belongs_to :client

	def create_time_card(client, card, time_start, time_end, time)
		client != "" ? client_id = client : client_id = ""
		card != "" ? card_id = card : card_id = ""
		time_start != "" ? start_time = time_start : start_time = ""
		time_end != "" ? end_time = time_end : end_time = ""
		time != "" ? time = client : time = ""
	end
 
  def format_time(time)
    t = time.to_i
    Time.at(t).utc.strftime("%H:%M:%S")
  end


end

app/controllers/time_cards_controller.rb
class TimeCardsController < ApplicationController
  before_action :set_time_card, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /time_cards
  # GET /time_cards.json
  def index
    @time_cards = TimeCard.all.where(user_id: current_user.id)
    @clients = Client.all.where(user_id: current_user.id)
    @cards = Card.all.where(user_id: current_user.id)
    @time_card_date= []
    TimeCard.all.where(user_id: current_user.id).map{|x| @time_card_date.push(x.created_at.strftime("%Y-%m-%d")) }
    @time_card_date = @time_card_date.uniq
  end

  # GET /time_cards/1
  # GET /time_cards/1.json
  def show
  end

  def list

  end

  # GET /time_cards/new
  def new
    @time_card = TimeCard.new
    @time_card.user_id = current_user.id
  end
  
  # GET /time_cards/1/edit
  def edit
  end
  
  # POST /time_cards
  # POST /time_cards.json
  def create
    @time_card = TimeCard.new(time_card_params)
    @time_card.user_id = current_user.id
    @time_card.total_time = @time_card.format_time(time_card_params[:recorded_time])

    respond_to do |format|
      if @time_card.save
        format.html { redirect_to @time_card, notice: 'Time card was successfully created.' }
        format.json { render :show, status: :created, location: @time_card }
      else
        format.html { render :new }
        format.json { render json: @time_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_cards/1
  # PATCH/PUT /time_cards/1.json
  def update
    respond_to do |format|
      if @time_card.update(time_card_params)
        format.html { redirect_to @time_card, notice: 'Time card was successfully updated.' }
        format.json { render :show, status: :ok, location: @time_card }
      else
        format.html { render :edit }
        format.json { render json: @time_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_cards/1
  # DELETE /time_cards/1.json
  def destroy
    @time_card.destroy
    respond_to do |format|
      format.html { redirect_to time_cards_url, notice: 'Time card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_card
      @time_card = TimeCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_card_params
      params.require(:time_card).permit(:description, :total_time, :recorded_time, :time, :date, :client_id, :card_id, :tag_id, :start_time, :end_time)
    end
end

app/helpers/time_cards_helper.rb
module TimeCardsHelper
end

app/views/time_cards/_form.html.erb
<%= form_with(model: time_card, local: true) do |form| %>
  <% if time_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(time_card.errors.count, "error") %> prohibited this time_card from being saved:</h2>

      <ul>
      <% time_card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-control">
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.time_select :start_time %>
  </div>

    <div class="field">
    <%= form.label :end_time %>
    <%= form.time_select :end_time %>
  </div>


  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :client %>
    <%= form.text_field :client_id %>
  </div>

  <div class="field">
    <%= form.label :card_id %>
    <%= form.text_field :card_id %>
  </div>

  <div class="field">
    <%= form.label :tag_id %>
    <%= form.text_field :tag_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
</div>
<% end %>

app/views/time_cards/edit.html.erb
<h1>Editing Time Card</h1>

<%= render 'form', time_card: @time_card %>

<%= link_to 'Show', @time_card %> |
<%= link_to 'Back', time_cards_path %>

app/views/time_cards/index.html.erb
<p id="notice"><%= notice %></p>
<br />

<%= tag.div id: :timer, data: { timecards: @time_cards.to_json, clients: @clients.to_json, cards: @cards.to_json(include: :listing)} %>
<br/>

<%= tag.div id: :timertable, data: { timecards: @time_cards.to_json(include: [:card, :client]), dates: @time_card_date.to_json} %>

app/views/time_cards/new.html.erb
<h1>New Time Card</h1>

<%= render 'form', time_card: @time_card %>

<%= link_to 'Back', time_cards_path %>

app/views/time_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @time_card.description %>
</p>

<p>
  <strong>Time:</strong>
  <%= @time_card.start_time.to_time %>
</p>

<p>
  <strong>Time:</strong>
  <%= @time_card.end_time %>
</p>

<p>
  <strong>Client:</strong>
  <%= @time_card.client_id %>
</p>

<p>
  <strong>Project:</strong>
  <%= @time_card.card_id %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @time_card.tag_id %>
</p>

<%= link_to 'Edit', edit_time_card_path(@time_card) %> |
<%= link_to 'Back', time_cards_path %>