config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :tags
  resources :clients
  resources :time_cards
  root to: 'clients#index'
  get 'index/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :listings do
    member do
      patch  :move
    end
  end

  resources :clients do
    member do
      get :to_do
    end
  end

  resources :time_cards do
    member do
      patch  :edit
    end
  end

  resources :cards do
    member do
      patch  :move
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  acts_as_list 
  scope :sorted, ->{ order(position: :desc) }
  belongs_to :listing
  belongs_to :client
  has_many :time_cards
  belongs_to :tag

  def update_attr_on_move(position, listing)
    if listing != nil 
      self.update_attribute(:listing_id, listing.to_i)
      self.save
    end
    if position != nil
      self.insert_at!(position.to_i)
      self.save
    end
    self.save!
  end

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy, :move]
  before_action :authenticate_user!

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.sorted.where(user_id: current_user.id)
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
    @card.user_id = current_user.id
  end

  # GET /cards/1/edit
  def edit
  end

  def move
    @card.update_attr_on_move(card_params[:position],card_params[:listing_id])
    render action: :show
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)
    @card.user_id = current_user.id

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:listing_id, :name, :position, :client_id, :user_id, :card_color, :tag_id)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :list_id %>
    <%= form.text_field :list_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.number_field :position %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>
<br />

<%= tag.div id: :cards, data: { cards: @cards.to_json(include: :listing)} %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>List:</strong>
  <%= @card.list %>
</p>

<p>
  <strong>Name:</strong>
  <%= @card.name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @card.position %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>